#!/bin/bash
# macports_updater.sh - Generated by macportsAssistant v3.0.0
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Error: Must be run as root (use sudo)"
    exit 1
fi

if ! command -v port >/dev/null 2>&1; then
    echo "Error: MacPorts not found"
    exit 1
fi

echo "Updating MacPorts..."
port -v selfupdate

echo "Upgrading outdated ports..."
port upgrade outdated

echo "Cleaning up..."
port uninstall inactive
port uninstall leaves
port reclaim

echo "Update completed successfully!"